# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://kelvinromero.github.io
baseurl: /
title: Kelvin Romero
email: kelvinromero@gmail.com
author: Kelvin Romero
description: >
  Staff Engineer writing about observability, distributed systems, and engineering productivity.
copyright: 'Copyright &copy; 2026 Kelvin Romero. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

markdown: kramdown
permalink: pretty
highlighter: rouge
future: true

kramdown:
  input: GFM
  syntax_highlighter: rouge

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    url: https://github.com/kelvinromero
  - title: linkedin
    url: https://linkedin.com/in/kelvinromero
